name: Build the site
on:
  push:
    branches: ["master"]
  schedule:
    - cron: "0 */12 * * *"

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: "scripts/go.mod"
          cache-dependency-path: "scripts/go.sum"

      - run: |
          go version
          go run main.go
        working-directory: "./scripts"
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          OVERRIDE_URL: ${{ secrets.OVERRIDE_URL }}

      - run: |
          GIT_HASH=$(git rev-parse --short HEAD)
          sed -i "s|./javascript|./javascript-${GIT_HASH}|g" index.html
          mv "./javascript" "./javascript-${GIT_HASH}"

          CURRENT_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          sed -i "s|CURRENT_DATE|$CURRENT_DATE|g" index.html
        working-directory: "./_site"

      - uses: actions/configure-pages@v5
        id: pages

      - uses: actions/upload-pages-artifact@v3
        with:
          path: "./_site"

      - uses: actions/deploy-pages@v4
        id: deployment
